name = "justatemp-postservice"
main = "src/index.ts"
compatibility_date = "2023-01-30"
kv_namespaces = [
  { binding = "POST_DB", id = "01d749f303f84eecb603e0a4f5eb149b", preview_id = "11cbcd4bc02342f38e2157fe4f554699" }
]